/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'contrast',
    path: '/contrast',
    component: 'layout.base',
    meta: {
      title: 'contrast',
      i18nKey: 'route.contrast',
      localIcon: 'TablerAB2',
      order: 7,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'contrast_verifyconfig',
        path: '/contrast/verifyconfig',
        component: 'view.contrast_verifyconfig',
        meta: {
          title: 'contrast_verifyconfig',
          i18nKey: 'route.contrast_verifyconfig',
          localIcon: 'MaterialSymbolsLightRoomPreferencesRounded',
          order: 5,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'contrast_verifydata',
        path: '/contrast/verifydata',
        component: 'view.contrast_verifydata',
        meta: {
          title: 'contrast_verifydata',
          i18nKey: 'route.contrast_verifydata',
          localIcon: 'VaadinOptions',
          order: 6,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'contrast_verifydetails',
        path: '/contrast/verifydetails',
        component: 'view.contrast_verifydetails',
        meta: {
          title: 'contrast_verifydetails',
          i18nKey: 'route.contrast_verifydetails',
          localIcon: 'VaadinOptions',
          order: 7,
          hideInMenu: true,
          roles: ['R_ADMIN']
        }
      }
    ]
  },
  {
    name: 'datasource',
    path: '/datasource',
    component: 'layout.base',
    meta: {
      title: 'datasource',
      i18nKey: 'route.datasource',
      localIcon: 'HugeiconsDatabaseSetting',
      order: 6,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'datasource_manage',
        path: '/datasource/manage',
        component: 'view.datasource_manage',
        meta: {
          title: 'datasource_manage',
          i18nKey: 'route.datasource_manage',
          localIcon: 'IconoirDatabaseTag',
          order: 1,
          roles: ['R_ADMIN']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      localIcon: 'MdiMonitorDashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      localIcon: 'CarbonCloudServiceManagement',
      order: 11,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          hideInMenu: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          localIcon: 'IcRoundManageAccounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true
        }
      }
    ]
  }
];
